sudo: required
services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - docker version
  - docker info

script:
 - mvn clean verify -f alma-server/pom.xml -e


after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker images
  - docker push equiperouge/alma-server:latest

deploy:
  provider: releases
  api_key: $API_KEY
  name: Build Travis $(date +'%d.%m.%Y %R')
  on:
    repo: equiperouge/alma-m2-2017
