sudo: required
services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - docker version
  - docker info

script:
  - mvn clean verify -f alma-server/pom.xml -e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker images
  - docker push mariobaptiste/alma-server:latest

deploy:
  provider: releases
  api_key: "ab3e8406e1d4f900d6dc61b021ea72557e14bada"
  file_glob:true
  file: *
  skip_cleanup: true
  on:
tags: true
