sudo: required
services:
- docker
language: java
jdk: oraclejdk8
branches:
  only:
  - master
before_install:
- docker version
- docker info
script:
- mvn clean verify -f alma-server/pom.xml -e
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker images
- docker push charlenemarie/alma-server:latest

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $PA_TOKEN
  name: Build Travis $(date + '%u, %d/%m/%Y, %T')
  on:
    tags: true
    repo: charlenemarie/alma-m2-2017
