sudo: required
services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - docker version
  - docker info

script:
  - mvn clean verify -f alma-server/pom.xml -e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker images
  - docker push arayabegaudeau/alma-server:latest


deploy:
  provider: releases
  api_key: 4408a47fc4afcde64db04ce33e7d3dee1de77bce
  name: Build Travis $(date +'%d.%m.%Y %R')
  on:
    repo: Araya-Begaudeau/alma-m2-2017